# Generated by Django 3.1.1 on 2020-09-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('move', models.CharField(max_length=10)),
                ('column', models.CharField(max_length=1)),
                ('player', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('winstatus', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
