# Generated by Django 3.1.1 on 2020-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect4api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movesdata',
            name='winstatus',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
